version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: stellar_db
    restart: always
    environment:
      POSTGRES_DB: master
      POSTGRES_USER: stellar
      POSTGRES_PASSWORD: stellar
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:Z
      - ./database:/docker-entrypoint-initdb.d:z
    networks:
      - dev_net

networks:
  dev_net:
    driver: bridge
