CREATE TABLE agency (
    id SERIAL PRIMARY KEY,
    bank_id INTEGER NOT NULL REFERENCES bank(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);